### ISSUE TITLE
Add check script

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/disrupt-o-meter#16]
Add shell script called `check.sh` to run the following commands:
- golint all Go source files
- go vet all Go source files
- misspell check on Markdown and Go source files
- shellcheck on all shell scripts

Add call to check script to Makefile as `check` target.

Add `check` target in Travis configuration before test.

**Comment by LynxPlay101** [comment]
What does go vet even do ? 

https://travis-ci.org/homeport/disrupt-o-meter/builds/482893155
This build also failed due to go vet, and worked perfectly fine after removing it in the next build.
